//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        public Model()
        {
            this.Computer = new HashSet<Computer>();
            this.Connection = new HashSet<Connection>();
            this.Device = new HashSet<Device>();
            this.Router = new HashSet<Router>();
            this.Queue = new HashSet<Queue>();
            this.Routine = new HashSet<Routine>();
            this.Server = new HashSet<Server>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Computer> Computer { get; set; }
        public virtual ICollection<Connection> Connection { get; set; }
        public virtual ICollection<Device> Device { get; set; }
        public virtual ICollection<Router> Router { get; set; }
        public virtual ICollection<Queue> Queue { get; set; }
        public virtual ICollection<Routine> Routine { get; set; }
        public virtual ICollection<Server> Server { get; set; }
    }
}
